---
apiVersion: v1
kind: Namespace
metadata:
  name: kapp-gitops-mgmt
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-sa
  namespace: kapp-gitops-mgmt
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kapp-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kapp-sa
    namespace: kapp-gitops-mgmt
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: pez-498-mgmt
  namespace: kapp-gitops-mgmt
spec:
  serviceAccountName: kapp-sa
  fetch:
    - git:
        url: https://github.com/tsfrt/cluster-mgmt
        ref: origin/dev
        secretRef:
          name: toms-github
  template:
    - sops:
        pgp:
          privateKeysSecretRef:
            name: pgp-key
    - ytt:
        ignoreUnknownComments: true
        paths:
        - "mgmt-cluster/noavi-mgmt/"
        - "mgmt-cluster/common"
        - "mgmt-cluster/env-config/noavi"
        - lib
    - kbld: {}
  deploy:
    - kapp: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: pgp-key
  namespace: kapp-gitops-mgmt
stringData:
  my.pk: |
    -----BEGIN PGP PRIVATE KEY BLOCK-----
    
    lQVYBGGqIxIBDADbggUMC4a8pbwhVRNeGGYovL9vhag+RS8SkjM9lx2Fmaf9rCxj
    LsBKBw8DvWKl7Cpk2ezF2RPztHqD+dFqy/3WI2phDjw7Sp1dGu+CrBhXsfnQndTt
    IQ7y1JLFdipI+2SOzcvwoDFtaZtMYwotnbxzaLyJ7JT1LxdmLhggFKnQBy9RRApU
    d9riHFopn4xBaJWuClxo3vYM7LXVbtD/UsRdOG4owvQiZf+Iu8TqfWnQMdnaUYUu
    zaJEyEhQmNWN+sFT6hpMHgcFrY6uDztnT7f0XceCXc7oQ0ZsFnCgf2p44wVJUcE/
    AkDtUL1vvS8kfZMry9AwdjogY5/RGhUbBE1kSFvSE1SZZtoFlNkdo0+enibPAmjB
    VB5ZKoX+/84YnKkSejV6X5TMqmqyHESgwVwt6kPLe0IdL5UYUbjqDy+aTf9wuYr/
    LZZGNBJXBRNE/5ewU5H9v9wHcZNkaZlmmx+SQLmmM3cTOX4dnyihPsJm+UAOG6y3
    YaSARCDTZRQebxcAEQEAAQAL/jvrKniGvvFI5mlM4VwKmfxdxX3qRKo21Woi2XTj
    Bq586qPutzEdxmSOt7UEIeT76ficmirJnk4kglr7OwSFiZVGFphGu/9NV1Zeb2nC
    k2SA0xn0s3ZFU2DK0QOwxUslwGXQ3G4jNErTDI7V7CXWjGYOfYTCvUiOYbtFMtWy
    /kWoaGys/4reKrQVHDGHeVAzfcRD1MTVs+GETgBkXw2LKMnviPZ8fQrUv+Oxqcd+
    k38+1GJpZUsI29Ydu8uwZH78pv7VSlWurtPoNr9hAvm4y7K4N+nWa+t7RcpZc5FK
    eGuxNu/GiHLKL2Cp7vKpuoa1Lh6N4KMTwWMboYUCXb20xREG1o4tf7DqC4nqDS1H
    n5FF2bahpyZ7iRVNsP7f55ji3vVyArbxO2qERGsH6i0nG2VLDF3IMqIEA+3QWiy6
    je/dx9jB27mFvQmKU8xo1lCQvgNE4G2bby6reYRdNNP1guW1ZJG8f1UOK684BGvk
    JfqbXDhygar5cdO44pYY/SBDJQYA6kLEuxYGdnMTLI6ko5BP/wFD+P/NIFyxIJKM
    soPh+V+waf8kc9t5vKMn1k5nPKhHWBzEZwfFfTX1R9pKlD8feh+yWc8tHq6zzmjM
    45iO7nRiVrVmlbKpNrd6BrVEmdkDuGBr9z1FfJOrfB0o4ibnZHDBDDOYdN/Dm26H
    f9ODnPm98r94pnmwD17LF3aJ/SW5MA5G1gX9pSn+dyP644PuCsBM+hIIywW4X0Ix
    Q4u+vqegKjUunxHzMpFXu4ZYKkwtBgDv4MXALsSdAim3ICX2UMpXB1/INlX0Pq+3
    ftq5ivIY0JqkKHzR+41YBrwI6a4iUpj/bCwfAASmFUQCdtpJt1Zt7WVKCz60s0qr
    xsCsBkpGF0dvmioSdroMCTDeEcMlcsoAr0g8WZsfwQQnDyd2qZ31YPWjVNnFo15S
    pbPr8YWW8dIqltE5G0u7pZXMzWlXjGLaz+QUeUwpgI37SulCI7Wt/dkpjrHA1gm9
    TvgRikLVMpEpKGkGDqRQkljqtquB/tMF/14APGy3dXmmsjIGEYFr17uslkEr10Ua
    q4qiwW4InxaehxFXGjlYShelfVgvB6CThQcb4brv0gupGYKHAZf5kauas7CJxbjH
    ywCx0xMUOHj+zG4rTNUHTe2RhR8nGpG4ddrLaj7A5eQj1fSviMfHdE2TUm1iKbXZ
    UeMyRTSkm+lBIPMjs2u7BCi+cahMEgw4xi+D02SzdoO/h6GQt/8oALA2rhdVcNLx
    lubTqSti2GxLZzKMYMBJ5A3NUmFMeBGMseY3tCBrYXBwLXVzZXIgPGthcHAtdXNl
    ckB2bXdhcmUuY29tPokB1AQTAQgAPhYhBCCn4wSX6OYMCxhp6sKo6H5/627OBQJh
    qiMSAhsDBQkDwmcABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEMKo6H5/627O
    9VIL/Az7ePY6VyrkRlJB4adpI66E3FajXN3FeR6jEyTyE2WeXvwZ6byv4FD6Ayn5
    VzxMnseo/KXhEDesN7IOInEN1zPHTsJ0z4dVE/+OpZ4bThYHfgIaPM+3xzaBO7Qn
    LHyI+6G+liTp81YFZTRsIaYXBMKkYmhQ/wh8gcNC0NqQvi3pfSdg3M1pHpr44HQz
    KbdRiWhfNRUzPDwFtL4e8BGoz+yTtvw36k9wWEQgDgLEROQndjZEToN6sCp4UMUl
    2+QakOo/58UD935QmeX/HoNKbtWNO07HF4JSwe8NmAXHjtIMhn/2OwZU4YFghIfS
    KstOOeJKVvqXAw4y54Z45eSZFnZHkFdQCFq9hQnGwxIbmJ0fT3FhUfqcft9Rhb2d
    QrHQCejgojLgJlqbNN28AyVVhrgM8ngYF+Pz897ryTDNYWreyNvD7YS72CV4i5U/
    9zZKWWD/HUbTmTdASZPt51JyMR4ERdFAN6i9szoDSfkvhlHKQnzJzM+0NUppTOdE
    XSCON50FWARhqiMSAQwAzixn1bQZSx7hk77/gGA81UxYvOrhZMqCMJenls3dh9J8
    usOezEnP5M0R83l1Gv71MZsR9eHA24eSz9HI/blDgjgMBLSPgDDmLhBh3NfP/09v
    z+q3/adf6ltIuyMtlquV3BlN5QQVBhuaA7EqwGH/Rz8G3e/DkwJnbRwxBqYfqApV
    5dMqLxNj2k6mopcqtlGnDXcSRoPYBKAq83aVytOFSPv1jAIIxUmasdnqG+iBQyU/
    M8j4nYtBUbEZZjw5woYC8WK1liY2LSxG/6jzHtQqY1ZkK4D9lkJ24pFvA8JnaHTd
    UOIGwiZsT5+D2pWws9fta7dktfvX3WXjOi0z37xnQ36x61sUCS4TWsudsjny9VDZ
    1shlJqeMtDg77OqNhgv13EYUFLPRKAGw7J9ig/PeuzCHcagOgBTphqmQBhVnkkip
    QL47XtTO4kKFw/s/9GRFwKTq0s6KL58ji054f99JP/ERmVsCcazywWwgKMykrvYT
    //Cudnz8DU6aVSOqXUQfABEBAAEAC/0X3liHtenHDRmvaZ7EcB/Kz85m0fMVy0Nc
    OHUXRoOy5uGNcPqQNawNldd8rknU6MGzzvs60eUVD90laxOPms71IzjyTdcJJQrD
    jXOkRhCB7bfeRGhYQ3QdZRkGn+bLY9edxgjYY8BtVxey/WPw0XI6Kifzh1TxztxG
    FkvvXvRuQgK6Gy1t4Br2GeySXoQm3E1wh8xEAUfVF+0xB2sFsrbiVq0RhZDEtPs6
    7iVQus+a2ZPiEmOvQCu9NzlfYRyMvR0ik/KcSCJMfKS9x7VFO49Y5eqAGci9buIz
    rh6Kw8y3HttSY4vL2pBq510GJg6LKjQiAFAE7jjoJqf3j1YH/WQKT1PRsEQxU+rJ
    ozOWTy2/zYQlOJUqGVNr11T0V5erYo4fOa4OoAOJCn8tm6O9g3chH2a6kn7d/FtF
    i+m771qyTASXU1F4xQeoHrVrS/Oap/bmu6CUNkJj9ojRnFvz6hdD75Kf94MhFL5E
    TzW2iuebCvorRoU0saqWxGexGgykn00GAOSPffgeZ6vPZBGBKieAonMhN95Qfux6
    GpUzvmxnZc+z02o+PYigKfshFDts2NrFQgxGTV90wlrt+dbdVZEnLUAduAHeS3xq
    NKVz31t6NFBqB8ONU8fRFrxUBbQioXsMvzfvnulpr3VzWHG4Zucf99ogq2QhK+Z+
    tXBAHyMj7xYpx/jthbYCLUpgRxgN/5YVjKyc4IEL/SELVAirFeGnH/t0qMarTdMK
    a+gq0GI/gjD4irHes/eONUoqlwZVZ3kPKwYA5uzgbv+PUiTc3XX6gAuxffN/z3XN
    9uwN3mFggTt0CcpMBQ5pxjaJUSTfWvGBujJwHctkpGCXP6/VbakJovMjeRKRj7Ah
    V50JG6KYrA37oFffSExEustGYcp2gn+L+4kvwUFGi5zWTQtqs9GNE7JV+BKJKEJb
    3cxZcTs2MXYtCNHbt/C23wW2VVyoEU/ojDXH2ah/S1OUEr84aZFxqys85ft8649q
    6K23kyRIPid6kdVA40o0BG8c2urLfQo0m4TdBfsEkdXKUINI+elGnzEZt/X7IXCq
    Rwb99zdRF2ZFEq0wTEcXZ5H63AVRZE1NraMuGns1D6xSnxqOKTAtxawEsC+T0nKY
    FIIQ2MEGKLuRl/iZLgovz5Yp9qeHsQwNLC1llJvoLjyRRbAy0UOIMjJ51pluSjSK
    Eu5LEEYBWAJuCQVGAoAHii6kGpoDN8FL6OvQ1Ea/IeFVCoUJu75x40p4DSQrhqyo
    AMvgvFZfX2SsLBp+piWZXqTjv/758tMc4WenDprQWYkBvAQYAQgAJhYhBCCn4wSX
    6OYMCxhp6sKo6H5/627OBQJhqiMSAhsMBQkDwmcAAAoJEMKo6H5/627OTZYL/3AV
    pz65NKHX230mP/lW52A28+mEVUNDZ2/fNLWDLbDpgZfntU/5MAeXeU8P1C5sXE3y
    2o4OzyWqTI+Aoj5LfRWKOfmRRDTjCFVDC1re5eMKT3EWBlooAazDS4WGk27ZsDPJ
    W/jzNcEV9wO889/1Z4xCmcydSPCvfimcPVl2uqwxu2YltRNtIAkFHVAL4yLn5eJG
    VtefPvGQrMHQMWgBCFxIbMlvztyLKAQHO5kr7vacWk4LKXf7AtfLlOCcZb6PPXGX
    LnyoOxmrayvG1DCE2D5nmMPVEFWwth+YZ2Va1povlpMMt9VvrbFzKnsUmiWjrjYT
    +varsHCQXKRZ4uTV1jzLG63gsE4aK2zk/cKTz2pOou2vKUzLXznHpg4wdSJB3sWB
    9CxXjBFI0/XYnKQP9RMiWb/aCpPuc+UuBRywRQby7RQH55PlV9CPtKYvY/p0tqoL
    lNDNtk5TuaB4gHQIM+O1XrakwPo3wvvNLe0ikya53YG14nKJofrfHO9i4DbEIg==
    =Zfea
    -----END PGP PRIVATE KEY BLOCK-----
---
apiVersion: v1
kind: Secret
metadata:
  name: toms-github
  namespace: kapp-gitops-mgmt
stringData:
  username: tseufert@gmail.com
  password: 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
---
apiVersion: v1
kind: Secret
metadata:
    name: vsphere-common-values
    namespace: kapp-gitops-mgmt
stringData:
    vsphere-common.yml: ENC[AES256_GCM,data:fonsai9FzNxxLhCUVngivFMh7pmFEWPIzSdjdkWBGkGP8IDcaZx+rpJbggkN182vZTmW9WsCcokWti7ZjK8a3dB0x4vO+SrJ2dmhBLGfs6lioTKBSp6RGeuS2uNcOj29b9LWYI46YHBbZNBQSoVsPPAlS4RyNnFNq6BTJTOw5hrzB2DXj4dSgENxuR6nSsKWBptK+dC7r4vl7Z1pCnEj3CX1xPIKpMMAXlWqWv+iUYxLjIom001ef9Z9w1B5lydZHU+fgY84loZu5CqOBZLobmfUsadWhS5aaRlbW93edBwkvrP2p/bHt43+qO79X58qFEGJtA7E5HOSSfZzwNWBpImhgEanfSJN5MvVrgS1D1p+iMkH7lBqcpXR/hXg7KALVmEoEYsIR6d2UZtJMVYFBfpcspcEpQxZQE8IrOU1vkCof7JvX21dwkxDBznpmmK5YxS400K7xyqQ+LXyMqRWcBZM5UTFpTKll6wZ42zlSHSnnoFMf/zAQV9h1Ci5teUluNGdyswa5EeA9bbxb0guruKZtdKImsic9rvpl+sacLbw/PU6Y3rWbrm52dz716sYpPYFWg9qQQyyTV5/vrvzCtuyxNqX9J13O4QDqfdN77pBHJkqu5f0qRrxRhLH01MP9xAMwadf9qH8n7D7Dkmm1XixOSB0wKmCtsW7w5EbOMKmmsdadXk77XiArt5L9WWNpokjE69KVroyktzbYds1Wx8cFk8wD9mdeKSDA75mEQl+eBEgYDvKOEvntHZ9ojfpiJu0UCX9r+AYuztEPgc4k89ZnMZypxjPrwumUyFzvrdJA/oQfhBbwqeysDpLinOsRXMmKJXgurGO6tYDdtKn6RH8S6vn5wp5bO/Wol+QRImBIA2rlKXH0eFxR8aG37EAOLa0DeKrvsK8yZSkeC7/6uKk2fHeNow6QEEUDMddoHuUp/5sMwZuiMQ6XARYP1UuLGAwArw3CYMXNYnGc1/VnUM6Sdlj5I2qA0mCUOoTnEb/g6yDWWMfinu5/X8MGGjllzk5TVowBy3DoCtL0vEI7gnceSXo7v9Iy/2Y9KSrHjUuzrPEO21mCeP1ktS97RSfcbNXmYV6gK2LdUBzdc17r2ht1L+VNTbj0rj4d6WM2ZbB7i3hR1zKxH16G9fkjK93XktJoF+zi1Tbyd76W9lGwUs2XdFQnvf9+UjtDd82FRNL3AFZfwMZdnTrcSe/AFyzQgzdgCaMp1gFLKuokyLg5NQTSC9M9PDSU1ePs2ujB+qhTU2oC+1cS7/gCRRL9y7jVtzDP0ncGBTa967CQOl57aD7l9u/3wxKDbwrAzlLIEAkiZVBLZDgeenGBW1PgFuK0lhwthjm0Fs1ef4FRIisrTfb6/HWd7xfecELc8hG6cVZKajAHmWruX78QP29OOpnpsEKj6FYC7huZBtk+SVl8g+j2Q9wyfa5RST9D4ZoKGSrBNMDoZPKYWOEaYONJIY5HNRLxe7cC+d3RNdDccgEQ4vP00f6Swop/6vUP+bqCtm2tvPy0pkO8FCSnZ9eHdhaguEZKDOTH/dcZWOcnOEQ00ZxnLqPCaWG8FCb8FRy5HwuOqNTTF+WA+g4UUi1R0FPTvr7pka2lZDpONkGOlne5aHcaZM9hEuvTMHz1+Tg2Za9tV2UtjUUSFYOB49IQnOxbAozvYtsJN4KVDZHjlQrBEfeRl6SzDioZqSTmbgK3AXby7zYtkdv+GaANnJNxqHFcyKsyx1DuAl9DrKH6YAHRkS8DaIBfJIUPt/r9FGL3I564gI+F9146ja/fDu7Ee89z4EuSCveUbnu49oxrJSHhejfK5XiZRaG6IxZk6aiyvpHKvzgdtd1UyUfEyIPLX8B+2jSOvX+13MlVFbj8nHVm9NrERk49Iwr+kzLK482TCOsrzB8cPrgoz2bBSMXFVLi9NGOLsnzqDh2ChRHOyyx6CUIoS1Q7spzkssKJGXBrAAV8owXRhmY93RB3BtkGfeXpwKpNInOgPlnE9174KHrJw5472IhOyh5n+p+yGfuf5PmFieja1qKT/GVwIlKhlDMbGV+O0RhCNLNp2/RLsOgGXysx3wzNdp+DxtL6UiPjmo58v9MJW//jjQmPDHrOdh3+UX8c6i7pELhEEmExDtofXgCIQJALK6ClaB2rS2VpL/Sn8/J2OiVBgIk5MZUQjgGw5Br0Ha3SQHTI8h2hn4UjtZez7DUWmJUyQxchjJuwB0XCdgaEtyWzx415aDduBGAy8EJpMd8v+3FZxiHnZxNpY60IWMwskx6FNfrTuNsDuMihbTS9dOuq+mt96UOTUemBA4A/zEK6CR828IZPAS7MyovOj8mDgKPGuAio+14SoA+4sbH3sLjHW3E2YcjWM+PBITpppM2wQy9K7SvURScAzu3xKIDs/g8f/zPqPfkfBCMh08ZcTz9v8ck0blstTHObzJWNogkPyQsXnq9XNVcTq6ITXkk8EuyvegSI2y8tGKV/1SVeYV7ubkpUPJ9eTN4RKG6UGRU0GM=,iv:qZxA4DE6fnLiMbaPZ3BP/F8hmklYb7Zt+CJe8KAySLk=,tag:bp9+EY8fFVDlnrBuMrnxRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-21T00:46:02Z"
    mac: ENC[AES256_GCM,data:FG3sEC6BeOWANKPQgF2UNHVqc67RwZxPcCAIQ/z7eZQdCU1HF0M9IhV85mCVGuTMOcchStn0PEiRQGK+s+Jyfd8SvEGPwxg/hZprWZLdrCNvnq+hEa14h+H1OI3OMrg1SMxBRNGODpNX/9voXaxW4xdwhmmT00C/V3+L+SCTDAE=,iv:EMKNxbe1Ffj+GnQJD0IpDn8nAhzc2yQ9DUjJzVoBSaA=,tag:psgKwTMrwVCd550qosIDNA==,type:str]
    pgp:
        - created_at: "2022-01-21T00:46:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0Zd9CCNvnZ+AQwAiv+5MGDjl5qmG70c3RhGXSJbULdis/NEgpovjcuoL/36
            ZUWHDFJw59cTOufXW5WpkfpZ9JpMAT8QnFLFktn74gXa0Grh79R5nDxoXPCCqfYb
            MIH25sXD5+anu6zBjWGLzL13cFjGij6JL6t6P3Qc8RB453geuN+FIQDnq7YKFNI6
            QdIm2GcZT9xTd3bD1+80sJPyTb3tcHhL6VIpAJepX+/QGyNI50jpkLc3IPg5O02T
            PtvqYreQoSHXwPEp/IeQrGqJO7d6IUKuI2Pc0fnzHYZKyWXZCtG9phpXY/Cp08Lh
            zAQv2mbxmd8buQhrgn9C8pPa6AUHdPXln+Q5xGra6NGHSIetl9lvLzTYiTSN0zvq
            Pk4qbvImBKfKpXGuUBqrdgIvTk1xgFpm76XIL8qV/D8Yg7mjmetOnSUqB0JDS10I
            bHlO3wJ7+DaFUyDQKZ4Z3tYhep+RHKovyNFQm6sFg7ITGphEwaPnPq3mvD2osdau
            ynshXS0IVcVMyo77Eb5T0l4BrCqL/nymA0NNXrz+0LgjFRdo9ad+rcDxE0W5mgGH
            fVPQ7FsBiBJSzH+qHldDThsvkdD6mGSVkNnIzCnKTGO+hSzYT/8/bXmCnjYqX4lO
            gKFLzPGkbqcwh71VPaDf
            =0CUe
            -----END PGP MESSAGE-----
          fp: C2A8E87E7FEB6ECE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1



