#!/bin/bash

export DEBUG=$(/root/setup/getOvfProperty.py "guestinfo.debug")
export HOSTNAME=$(/root/setup/getOvfProperty.py "guestinfo.hostname")
export IP_ADDRESS=$(/root/setup/getOvfProperty.py "guestinfo.ipaddress")
export NETMASK=$(/root/setup/getOvfProperty.py "guestinfo.netmask" | awk -F ' ' '{print $1}')
export GATEWAY=$(/root/setup/getOvfProperty.py "guestinfo.gateway")
export DNS_SERVER=$(/root/setup/getOvfProperty.py "guestinfo.dns")
export DNS_DOMAIN=$(/root/setup/getOvfProperty.py "guestinfo.domain")
export NTP_SERVER=$(/root/setup/getOvfProperty.py "guestinfo.ntp")
export ROOT_PASSWORD=$(/root/setup/getOvfProperty.py "guestinfo.root_password")
export HARBOR_PASSWORD=$(/root/setup/getOvfProperty.py "guestinfo.harbor_password")
export DOCKER_NETWORK_CIDR=$(/root/setup/getOvfProperty.py "guestinfo.docker_network_cidr")

export VM_DATASTORE=$(/root/setup/getOvfProperty.py "guestinfo.datastore")
export VM_NETWORK=$(/root/setup/getOvfProperty.py "guestinfo.network")
export VM_FOLDER=$(/root/setup/getOvfProperty.py "guestinfo.folder")
export VM_DATACENTER=$(/root/setup/getOvfProperty.py "guestinfo.datacenter")
export DEST_REG=$(/root/setup/getOvfProperty.py "guestinfo.hostname")
export VSPHERE_PASSWORD=$(/root/setup/getOvfProperty.py "guestinfo.vsphere_password")
export VSPHERE_USER=$(/root/setup/getOvfProperty.py "guestinfo.vsphere_user")
export SSH_KEY=$(/root/setup/getOvfProperty.py "guestinfo.ssh_key")
export VSPHERE_HOST=$(/root/setup/getOvfProperty.py "guestinfo.vsphere_host")
export VM_CLUSTER=$(/root/setup/getOvfProperty.py "guestinfo.cluster")
export ENDPOINT_IP=$(/root/setup/getOvfProperty.py "guestinfo.endpoint_ip")
export CLUSTER_NAME=$(/root/setup/getOvfProperty.py "guestinfo.cluster_name")

export MGMT_CONTEXT=$(/root/setup/getOvfProperty.py "guestinfo.mgmt_context")
export IMGPKG_REF=$(/root/setup/getOvfProperty.py "guestinfo.imgpkg_ref")
export GIT_PASSWORD=$(/root/setup/getOvfProperty.py "guestinfo.git_user_password")
export GIT_USER=$(/root/setup/getOvfProperty.py "guestinfo.git_user")
export GIT_BRANCH=$(/root/setup/getOvfProperty.py "guestinfo.git_branch")
export GIT_REPO=$(/root/setup/getOvfProperty.py "guestinfo.git_repo")